## Numpy 


Numpy library adalah salah satu library untuk scientific computing.

In [ ]:
# biasain Lakuin hal ini disetiap import library

import numpy as np

print(f"Version Numpy : {np.__version__}")

Version Numpy : 1.19.5


In [ ]:
# Set np.random.seed biar reproducible
np.random.seed(10)
print(np.random.randint(1, 9, size=10))

[2 6 5 8 1 2 4 5 2 6]


## Perbandingan kecepatan Numpy array dengan built in array

In [ ]:
import numpy
import time
 
# size of arrays and lists
size = 10000000  
 
# declaring lists
list1 = range(size)
list2 = range(size)
 
# declaring arrays
array1 = numpy.arange(size) 
array2 = numpy.arange(size)
 
# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
 
# calculating execution time
print("Time taken by Lists :",
      (time.time() - initialTime),
      "seconds")
 
# NumPy array
initialTime = time.time()
resultantArray = array1 * array2
 
# calculating execution time
print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")

Time taken by Lists : 1.2008934020996094 seconds
Time taken by NumPy Arrays : 0.01897144317626953 seconds


## Basic Numpy arrays yang bakalan dibahas
- Create Matrix & vector
- Attributes dari Numpy
- Indexing Numpy
- Slicing numpy
- Reshaping Array
- Join & Split Array
- Conditional Array


### Creating Matrix & Vector 
Buanyaakk banget caranya
tapi kami cuma ngasih beberapa saja yang umum

In [ ]:
# Vector random

np.random.seed(10)
print(np.arange(10), '\n')
print(np.ones(shape=(10), dtype=np.float32), '\n')
print(np.zeros(shape=(10, 1), dtype=np.int32), '\n')
print(np.random.randn(10), '\n')
print(np.random.randint(1, 11, size=10), '\n')
print(np.array([1, 2, 3, 4], dtype=np.int32), '\n')

print("====================== MATRIX SECTION ====================")
# Matrix
print(np.ones(shape=(4, 4)), '\n')
print(np.zeros(shape=(7, 7)), '\n')
print(np.array([[1, 2, 3], [1, 4, 5], [2, 3, 4]]), '\n')
print(np.eye(N=3, M=10, k=5), '\n')

[0 1 2 3 4 5 6 7 8 9] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]] 

[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021] 

[ 2  9  5  2  4  7  6  4 10  7] 

[1 2 3 4] 

====================== MATRIX SECTION ====================
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

[[1 2 3]
 [1 4 5]
 [2 3 4]] 

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]] 



## Attributes Numpy
Attr nya gausah dihafal ,sering aja dipake ntar juga nyantol

In [ ]:
np.ndarray?

In [ ]:
np.random.seed(10)
randArray = np.array([[5, 22, 1], [2, 34, 4], [4, 3, 2]])
print(f"type : {type(randArray)} dengan Nilai : \n{randArray} ")
print()

type : <class 'numpy.ndarray'> dengan Nilai : 
[[ 5 22  1]
 [ 2 34  4]
 [ 4  3  2]] 



In [ ]:
print(f"Transpose : \n{randArray.T}")
print(f"\nDimension : \n{randArray.ndim}")
print(f"\nShape : \n {randArray.shape}")
print(f"\nSize : \n {randArray.size}")
print(f"\nitemSize : \n {randArray.itemsize} bytes")
print(f"\ndtype : \n{randArray.dtype}")

Transpose : 
[[ 5  2  4]
 [22 34  3]
 [ 1  4  2]]

Dimension : 
2

Shape : 
 (3, 3)

Size : 
 9

itemSize : 
 4 bytes

dtype : 
int32


In [ ]:
print(len(randArray))
print(randArray.size)

3
9


In [ ]:
# a.T * a == kuadrat dari a
print(randArray.T * randArray, '\n')
print(randArray * randArray.T)

[[  25   44    4]
 [  44 1156   12]
 [   4   12    4]] 

[[  25   44    4]
 [  44 1156   12]
 [   4   12    4]]


## Indexing Numpy
Cukup Ez ya indexing itu , intinya tujuan indexing ya ngambil data 


In [ ]:
print(randArray)

[[ 5 22  1]
 [ 2 34  4]
 [ 4  3  2]]


In [ ]:
print(f"Index 0 : {randArray[0]}")
print(f"index 0,1 : {randArray[0,1]}")
print(f"index 0,1 : {randArray[0][1]}")

Index 0 : [ 5 22  1]
index 0,1 : 22
index 0,1 : 22


In [ ]:
#dapatin index maximum
print(f"index maximum = {randArray.argmax()}")

#dapatin index minimum
print(f"index minimum = {randArray.argmin()}")

#ini untuk sorting value tapi yang diambil indexnya
print(f"sorting value =\n{randArray.flatten().argsort()}")

index maximum = 4
index minimum = 2
sorting value =
[2 3 8 7 5 6 0 1 4]


In [ ]:
index0 = randArray[0]
print(f"type {type(index0)} : nilai { index0 } ")

type <class 'numpy.ndarray'> : nilai [ 5 22  1] 


In [ ]:
print("min : ", index0.min())
print("max : ", index0.max())
print("shape : ", index0.shape)
print("size : ", index0.size)
print("reshape : \n", index0.reshape((3, 1)))
print("reshape.shape : ", index0.reshape(3, 1).shape)  # Chaining

min :  1
max :  22
shape :  (3,)
size :  3
reshape : 
 [[ 5]
 [22]
 [ 1]]
reshape.shape :  (3, 1)


## Array Slicing . < MEMOTONG >
### x[start:stop:step]

![numpySlicing.jpg](attachment:numpySlicing.jpg)

In [ ]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr[1, 2:4]

array([7, 8])

In [ ]:
arr[:, 1]

array([ 2,  6, 10, 14])

In [ ]:
arr[2:, 2:]

array([[11, 12],
       [15, 16]])

In [ ]:
arr[1::2, ::2]

array([[ 5,  7],
       [13, 15]])

In [ ]:
arr[::-1, ::-1]

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

##  Reshaping & manipulate dims in Numpy array 
 Intinya nge reshape data \n
 Tips :
 - Cek Shapenya
 - Gunakan perkalian agar hasil perkalian pada shapenya sama 

In [ ]:
arr = np.arange(1, 19).reshape(3, 3, 2)

print(f"Shape {arr.shape}\n")
print(f"arr normalnya gini:\n {arr}")
print(f"\nabis di reshape \n{arr.reshape(6,3)}")

Shape (3, 3, 2)

arr normalnya gini:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

abis di reshape 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
# adding dims
arr = np.arange(6).reshape(3, 2)
print(f"awalnya shapenya gini {arr.shape}")
print(f"expand bagian belakang {np.expand_dims(arr,axis=2).shape}")
print(f"expand bagian tengah {arr[:,np.newaxis,...].shape}")
print(f"expand bagian depan {arr[np.newaxis,...].shape}")

#kalau misalkan di print sih gini

print("\n\n kalo di print")
print(f"normal \n{arr}")
print(f"\nexpand bagian belakang \n{np.expand_dims(arr,axis=2)}")
print(f"\nexpand bagian belakang \n{arr[:,np.newaxis,...]}")
print(f"\nexpand bagian depan\n {arr[np.newaxis,...]}")

awalnya shapenya gini (3, 2)
expand bagian belakang (3, 2, 1)
expand bagian tengah (3, 1, 2)
expand bagian depan (1, 3, 2)


 kalo di print
normal 
[[0 1]
 [2 3]
 [4 5]]

expand bagian belakang 
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

expand bagian belakang 
[[[0 1]]

 [[2 3]]

 [[4 5]]]

expand bagian depan
 [[[0 1]
  [2 3]
  [4 5]]]


In [ ]:
# Removing Dims
arr = np.ones(shape=(3, 2))
print((arr[:, np.newaxis, np.newaxis, ...]).shape)
print(np.squeeze(arr[:, np.newaxis, np.newaxis, ...]).shape)

(3, 1, 1, 2)
(3, 2)


## Join And Splitting Numpy 


### Splitting
Well Nge split ya memecah


In [ ]:
arr = np.arange(10)
print(f"{np.array_split(arr,indices_or_sections=5,axis=0)}\n")
print(f"{np.array_split(arr,indices_or_sections=4,axis=0)}\n")
print(f"{np.array_split(arr,indices_or_sections=8,axis=0)}\n")

#dia di pecah jadi sub array tar bisa kita print
x = np.array_split(arr, indices_or_sections=5, axis=0)

for arr in x:
    print(arr)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

[array([0, 1]), array([2, 3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [ ]:
arr = np.arange(20).reshape((2, 10))
print(arr, "\n")
print(f"{np.array_split(arr,indices_or_sections=5,axis=1)}\n")
print(f"{np.array_split(arr,indices_or_sections=4,axis=1)}\n")
print(f"{np.array_split(arr,indices_or_sections=8,axis=1)}\n")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

[array([[ 0,  1],
       [10, 11]]), array([[ 2,  3],
       [12, 13]]), array([[ 4,  5],
       [14, 15]]), array([[ 6,  7],
       [16, 17]]), array([[ 8,  9],
       [18, 19]])]

[array([[ 0,  1,  2],
       [10, 11, 12]]), array([[ 3,  4,  5],
       [13, 14, 15]]), array([[ 6,  7],
       [16, 17]]), array([[ 8,  9],
       [18, 19]])]

[array([[ 0,  1],
       [10, 11]]), array([[ 2,  3],
       [12, 13]]), array([[ 4],
       [14]]), array([[ 5],
       [15]]), array([[ 6],
       [16]]), array([[ 7],
       [17]]), array([[ 8],
       [18]]), array([[ 9],
       [19]])]



In [ ]:
arr = np.ones(shape=(10, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Vertical Stacking ,

# Rules Vertikal Simple : Total Columns Harus Sama
arr1 = np.ones(shape=(1, 10))
arr2 = np.zeros(shape=(5, 10))
print(np.vstack((arr1, arr2)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Horizontal Stacking ,

# Rules horizontal Simple : Total rows Harus Sama
arr1 = np.ones(shape=(5, 2))
arr2 = np.zeros(shape=(5, 1))
print(np.hstack((arr1, arr2)))

[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]


### Numpy Conditionals
- conditional langsung
- np.where()
- np.argwhere()
- np.select()

In [ ]:
#conditional langsung
x = np.logical_and(arr1 >= 0.65, arr1 <= 0.79)
print(f"ini klo diliat langsung conditionalnya \n{x}")

print(f"\nini cara manfaatinnya \n{arr1[x]}")

#dia bakal langsung ngambil yang true aja

NameError: ignored

In [ ]:
np.random.seed(10)
arr1 = np.random.rand(5, 2)
print(f"kita lihat isinya:\n{arr1}")

print(f"\nkita cari yang >0.65 =\n {np.where(arr1 > 0.65,arr1,0)}\n")
print(
    f"kita cari tapi yang dikembaliin indicesnya aja:\n{np.argwhere(arr1 > 0.65)}\n"
)  # indicesnya doang

kita lihat isinya:
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.16911084 0.08833981]]

kita cari yang >0.65 =
 [[0.77132064 0.        ]
 [0.         0.74880388]
 [0.         0.        ]
 [0.         0.76053071]
 [0.         0.        ]]

kita cari tapi yang dikembaliin indicesnya aja:
[[0 0]
 [1 1]
 [3 1]]



In [ ]:
print(f"ini array aslinya:\n{arr1}")
condList = [
    np.logical_and(arr1 >= 0.65, arr1 <= 0.79),
    np.logical_or(arr1 < 0.65, arr1 > 0.79)
]
choiceList = [1, False]
np.select(condList, choiceList, default=np.nan)

ini array aslinya:
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.16911084 0.08833981]]


array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.]])